fix: Set `repr(transparent)` on `NodeId`
AccessKit/accesskit pull request #216
Opened 2023-02-19 14:29 UTC by mwcampbell

This should help with FFI.

2023-02-19 14:35 UTC, DataTriny commented
@mwcampbell If you really want to tackle this separately from a following C bindings PR, then check out my [branch](https://github.com/DataTriny/accesskit/tree/c_bindings) because there are a lot of other places that require attention.

2023-02-19 14:41 UTC, DataTriny requested changes

2023-02-19 14:41 UTC, DataTriny commented on common/src/lib.rs
> +#[repr(transparent)]
Currently, on all types that have a `#repr(...)] attribute, it comes last, just before the actual struct declaration. I'd suggest moving it after the `#cfg|...]` attributes to be consistent.

2023-02-20 14:03 UTC, mwcampbell commented
I decided to go with `repr(u8)` on the enums rather than `repr(C)`, because most of our enums have a very small number of values, and even `Role` seems unlikely to exceed 256 values in the future, considering how comprehensive the set of roles from Chromium is.

2023-02-20 17:33 UTC, DataTriny commented
@mwcampbell I indeed agree with you. I just forgot that I didn't touch on `ActionData` yet because I wasn't sure on how it would be represented on the C side. But now that I've read a bit more about FFI, I think `#[repr(C)]` makes more sense here.

2023-02-20 17:35 UTC, mwcampbell commented
Do you mean we should use `repr(C)` in all the places where I just added `repr(u8)`? If so, why? I don't think an enum with fields, like `ActionData`, can be directly represented in the C API. Not sure what to do about that.

2023-02-20 17:51 UTC, DataTriny commented
I agree with all the changes you made. I was just referring to `ActionData`. I think it can be represented with `#[repr(C)]` since all the variants have a single field so it's kind of a tagged union. I can deal with this in my C bindings PR if you are not comfortable introducing this change right now.

2023-02-20 18:42 UTC, DataTriny approved these changes
Nice, thanks for that! Don't forget to update the commit title to mention the other changes.

2023-02-20 18:45 UTC, merged