Add sub roles to MacOS adapter
AccessKit/accesskit pull request #480
Opened 2024-10-31 22:07 UTC by HolgerGottChristensen

Adds initial support for accessibility sub roles to the MacOS adapter, allowing AccessKit to expose Toggle buttons, Switch and more, correctly to VoiceOver.

Needed clarifications:
* Does AccessKit handle math, and all the math roles from chromium?
* How is search box represented? [Role from MacOS](https://developer.apple.com/documentation/appkit/nsaccessibilitysearchfieldsubrole?language=objc)
* How is secure textfields handled? [Role from MacOS](https://developer.apple.com/documentation/appkit/nsaccessibilitysecuretextfieldsubrole?language=objc)

2024-10-31 22:16 UTC, DataTriny commented
> How is search box represented?

By giving `Role::SearchInput` to a node.

> How is secure textfields represented?

By giving `Role::PasswordInput` to a node.

2024-11-01 06:28 UTC, HolgerGottChristensen commented
I dont see any of the math roles in the list of roles: https://github.com/AccessKit/accesskit/blob/main/common/src/lib.rs#L55

Are they defined somewhere else?

2024-11-01 09:04 UTC, DataTriny commented
Woops, sorry. We must have removed them at some point. Please do the same.

2024-11-01 10:36 UTC, DataTriny commented
With the changes from this PR, tabs are correctly announced as tabs by VoiceOver. This can be tested by running the gallery example from [my fork of Slint](https://github.com/DataTriny/slint/tree/update-accesskit). I've updated the PR description accordingly.

2024-11-01 10:41 UTC, mwcampbell commented
I don't recall dropping math roles. It's more likely that when I copied the roles from Chromium in July 2021, those roles didn't exist yet.

2024-11-01 16:14 UTC, HolgerGottChristensen commented
> I don't recall dropping math roles. It's more likely that when I copied the roles from Chromium in July 2021, those roles didn't exist yet.

Yes, they were added in October 2021, so right after you copied the roles :)
https://github.com/chromium/chromium/commit/6ee95856677e69393c28b5c03142d29e79e69c49

2024-11-01 16:26 UTC, DataTriny requested changes

2024-11-01 16:26 UTC, DataTriny commented on platforms/macos/src/node.rs
> +fn ns_sub_role(node: &Node) -> &'static NSAccessibilitySubrole {
```suggestion
fn sub_role(node: &Node) -> &'static NSAccessibilitySubrole {
```

2024-11-01 16:26 UTC, DataTriny commented on platforms/macos/src/node.rs
> +            }
```suggestion
            Role::Button if node.toggled().is_some() => NSAccessibilityToggleSubrole,
```

2024-11-01 16:26 UTC, DataTriny commented on platforms/macos/src/node.rs
> +            self.resolve(ns_sub_role)
```suggestion
            self.resolve(sub_role)
```

2024-11-01 16:39 UTC, DataTriny approved these changes
Thank you @HolgerGottChristensen!

2024-11-01 16:40 UTC, merged